import 'package:flutter/material.dart';
import 'package:percent_indicator/percent_indicator.dart';
import 'package:provider/provider.dart';
import 'package:smart_routine_planner/models/http_exception.dart';
import 'package:smart_routine_planner/screens/create_plan_screen.dart';

import '../providers/plan.dart';

class AutoGeneratePlan extends StatefulWidget {
  // const AutoGeneratePlan({ Key? key }) : super(key: key);
  static final routeName = '/auto-generate';

  @override
  _AutoGeneratePlanState createState() => _AutoGeneratePlanState();
}

class _AutoGeneratePlanState extends State<AutoGeneratePlan> {
  bool _bannerVisible = true;
  var _bannerText = 'Please wait while your plan is being generated.';
  var _progress = 0;
  Future future;
  @override
  void initState() {
    future = checkStatus();
    super.initState();
  }

  void _showErrorDialog(String message) {
    showDialog(
      barrierDismissible: false,
      context: context,
      builder: (ctx) => AlertDialog(
        title: Text('An Error Occurred!'),
        content: Text(message),
        actions: <Widget>[
          TextButton(
            child: Text('Okay'),
            onPressed: () {
              Navigator.of(ctx).pop();
              Navigator.of(ctx).pop();
            },
          )
        ],
      ),
    );
  }

  Future<void> checkStatus() async {
    try {
      var response = await Provider.of<Plan>(context, listen: false)
          .getAutoGeneratedPlan();
      if (response.containsKey('success')) {
        _progress = 0;
        setState(() {
          _progress = _progress;
        });
      } else if (response.containsKey('progress')) {
        _progress = response['progress'];
        setState(() {
          _progress = _progress;
        });
      } else if (response.containsKey('msg')) {
        _showErrorDialog(response['msg']);
      } else {
        Navigator.of(context).pushReplacementNamed(CreatePlanScreen.routeName);
      }
    } on HttpException catch (err) {
      print(err);
    } catch (err) {
      print(err);
    }
  }

  _hideBanner() {
    setState(() {
      _bannerVisible = false;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Auto Generated Plan"),
      ),
      body: FutureBuilder(
        future: future,
        builder: (ctx, snapshot) =>
            snapshot.connectionState == ConnectionState.waiting
                ? Center(
                    child: CircularProgressIndicator(),
                  )
                : RefreshIndicator(
                    onRefresh: checkStatus,
                    child: ListView(
                      children: [
                        if (_bannerVisible)
                          MaterialBanner(
                            content: Text(_bannerText),
                            actions: [
                              TextButton(
                                child: Text('DISMISS'),
                                onPressed: _hideBanner,
                              )
                            ],
                          ),
                        SizedBox(
                          height: 50,
                        ),
                        if (_progress != null)
                          Column(
                            mainAxisSize: MainAxisSize.min,
                            children: [
                              CircularPercentIndicator(
                                radius: 200.0,
                                lineWidth: 10.0,
                                percent: _progress / 100,
                                center: Text(
                                  "$_progress%",
                                  style: TextStyle(fontSize: 40),
                                ),
                                progressColor: Colors.green,
                              ),
                              SizedBox(
                                height: 40,
                              ),
                              Text(
                                'Hold on, your plan is being generated.',
                                style: TextStyle(
                                    fontSize: 16, fontWeight: FontWeight.w500),
                              ),
                              SizedBox(
                                height: 20,
                              ),
                              Text('Swipe ⬇ down to refresh'),
                            ],
                          )
                      ],
                    ),
                  ),
      ),
    );
  }
}
